import Head from 'next/head';
import Link from 'next/link';
import Image from 'next/image';
import Router from 'next/router';
import { getSession } from 'next-auth/react';
import { useTranslations } from 'next-intl';
import React, { useEffect, useState, useCallback } from 'react';
import { useDispatch, useSelector } from 'react-redux';
import { paginatedItemsSelector, showDatePopupSelector } from '@/redux/dashboard/selectors';
import { paginationSelectorFactory } from '@/redux/layouts/selectors';
import { userSelector } from '@/redux/user/selectors';
import { fetchItemsAction, showDateSelectorAction, showPopupAction } from '@/redux/dashboard';
import { setPaginationAction } from '@/redux/layouts';
import { PaginationType } from '@/constants';
import { DateRangePicker } from 'react-date-range';
import moment from 'moment';

import 'react-date-range/dist/styles.css'; // main css file
import 'react-date-range/dist/theme/default.css'; // theme css file
import { activeTabSelectorFactory } from '@/redux/layouts/selectors';
import {AddClinic} from "@/components/clinics";


export default function Index({ session, locale }: { session: any; locale: string }) {
    if (!session) return <></>;
    // eslint-disable-next-line react-hooks/rules-of-hooks
    const dispatch = useDispatch();
    // eslint-disable-next-line react-hooks/rules-of-hooks
    const activeTabLayout = useSelector(activeTabSelectorFactory('clinics'));

    console.log(activeTabLayout);

    // eslint-disable-next-line react-hooks/rules-of-hooks
    const t = useTranslations();

    // const handleAddProduct = () => {
    //     dispatch(
    //         setActivePageAction({
    //             type: 'clinic',
    //             modifier: 'add'
    //         })
    //     );
    // };

    return (
        <>
            <Head>
                <title>DenTal Care - Clinics</title>
                <meta name="description" content="Generated by create next app"/>
                <link rel="icon" href="/images/logo-1.svg"/>
            </Head>

            <div className="page-title">
                <h1>{t('Add Clinic')}</h1>
            </div>
            <div className="page-content">
                <div className="card">
                    <AddClinic locale={locale}  />
                </div>
            </div>
        </>
    );
}

export async function getServerSideProps(context: any) {
    const {locale} = context;
    const session = await getSession(context);

    if (!session) {
        return {
            redirect: {destination: `/${locale === 'fr' ? '' : `${locale}/`}auth/signin`}
        };
    }

    return {
        props: {
            session,
            locale,
            messages: {
                ...require(`../../messages/${locale}.json`)
            }
        }
    };
}
