import Head from 'next/head';
import Link from 'next/link';
import { getSession } from 'next-auth/react';
import { useTranslations } from 'next-intl';
import React, { useEffect, useState, useCallback } from 'react';
import { useDispatch, useSelector } from 'react-redux';
import { userSelector } from '@/redux/user/selectors';
import { activeTabSelectorFactory } from '@/redux/layouts/selectors';
import { ListData } from "@/components/stores";

export default function Index({ session, locale }: { session: any; locale: string }) {
    if (!session) return <></>;
    // eslint-disable-next-line react-hooks/rules-of-hooks
    const user = useSelector(userSelector);
    // eslint-disable-next-line react-hooks/rules-of-hooks
    const dispatch = useDispatch();
    // eslint-disable-next-line react-hooks/rules-of-hooks
    const activeTabLayout = useSelector(activeTabSelectorFactory('clinics'));

    // eslint-disable-next-line react-hooks/rules-of-hooks
    const t = useTranslations();

    return (
        <>
            <Head>
                <title>DenTal Care - Stores</title>
                <meta name="description" content="Generated by create next app"/>
                <link rel="icon" href="/images/logo-1.svg"/>
            </Head>

            <div className="page-title">
                <h1>{t('Stores')}</h1>
            </div>
            <div className="page-content">
                <div className="card card-page">
                    <div className="flex flex-wrap justify-between items-center gap-2 p-6">
                        <Link href={'/stores/add'} legacyBehavior>
                            <a className="btn bg-danger text-sm font-medium text-danger hover:text-white hover:bg-danger max-w-[200px]">
                                <i className="b-icons btn-plus-icon"/>
                                <span className="s-caption">{t('Add Store')}</span>
                            </a>
                        </Link>
                    </div>
                    <div className="clearfix" />
                    <div className="relative overflow-x-auto">
                        <div className={`w-full ${activeTabLayout.tab !== 'list' ? 'hidden' : ''}`}>
                            {user?.id && <ListData locale={locale}/>}
                        </div>
                    </div>
                </div>
            </div>
        </>
    );
}

export async function getServerSideProps(context: any) {
    const {locale} = context;
    const session = await getSession(context);

    if (!session) {
        return {
            redirect: {destination: `/${locale === 'fr' ? '' : `${locale}/`}auth/signin`}
        };
    }

    return {
        props: {
            session,
            locale,
            messages: {
                ...require(`../../messages/${locale}.json`)
            }
        }
    };
}
