export default {
    "address_line_1": "Amedeo Digital Solutions OÜ",
    "address_line_2": "Tatari 25 - 4",
    "address_line_3": "10116, Tallinn, Estonie",
    "Item": "Item",
    "Description":"Description",
    "Unit Cost":"Unit Cost",
    "Quantity":"Quantity",
    "Line Total":"Line Total",
    "Invoice":"Invoice",
    "Shipping Amount":"Shipping Amount",
    "Subtotal":"Subtotal",
    "Payment is due within 15 days. Thank you for your business.":"Payment is due within 15 days. Thank you for your business.",
    "Invoice number:": "Invoice number:",
    "Invoice Date:":"Invoice Date:",
    "Refund number:": "Refund number:",
    "Refund Date:":"Refund Date:",
    "Balance Due:":"Paid Amount:",
    "Refund Due:":"Refunded Amount:",
    "Total Payment":"Total Payment",
    "Refund Payment":"Total refunded",
    "Delivery Address": "Delivery Address: ",
    "Transaction ID": "Transaction ID: ",
    "Holder Name": "Holder Name: ",
    "Payment Method": "Payment Method: ",
    "Refund": "Refund",
    "color": "color",
    "size": "size",
    "Shipping refund": "Shipping refund:",
    "Shipping refund1": ""
}
