export default {
    "address_line_1": "Amedeo Digital Solutions OÜ",
    "address_line_2": "Tatari 25 - 4",
    "address_line_3": "10116, Tallinn, Estonie",
    "Item": "Article",
    "Description":"Description",
    "Unit Cost":"Coût unitaire",
    "Quantity":"Quantité",
    "Line Total":"Total de la ligne",
    "Invoice":"Facture",
    "Shipping Amount":"Montant des frais de port",
    "Subtotal":"SubTotal",
    "Payment is due within 15 days. Thank you for your business.":"Le paiement est dû dans les 15 jours. Merci pour votre entreprise.",
    "Invoice number:": "Numéro de facture:",
    "Invoice Date:":"Date de Facturation:",
    "Refund number:": "Numéro de remboursement:",
    "Refund Date:":"Date de remboursement:",
    "Balance Due:":"Montant Payé:",
    "Refund Due:":"Refunded Amount:",
    "Total Payment":"Paiement Total",
    "Refund Payment":"Total refunded",
    "Delivery Address": "Adresse de livraison: ",
    "Transaction ID": "Identifiant de transaction: ",
    "Holder Name": "Nom du titulaire: ",
    "Payment Method": "Mode de paiement: ",
    "Refund": "Remboursement",
    "color": "couleur",
    "size": "taille",
    "Shipping refund": "Remboursement",
    "Shipping refund1": "des frais de port:"
}
