import Head from 'next/head';
import { getSession } from 'next-auth/react';
import { useTranslations } from 'next-intl';
import React, { useEffect } from 'react';
import { useDispatch, useSelector } from 'react-redux';
import { useRouter } from 'next/router';
import {AddClinic, ListData} from "@/components/clinics";
import { fetchItemAction } from "@/redux/clinics/actions";
import { clinicItemSelector } from "@/redux/clinics/selectors";
import { userSelector } from "@/redux/user/selectors";
import Link from "next/link";


export default function Index({ session, locale }: { session: any; locale: string }) {
    if (!session) return <></>;
    // eslint-disable-next-line react-hooks/rules-of-hooks
    const dispatch = useDispatch();
    // eslint-disable-next-line react-hooks/rules-of-hooks
    // const clinicData = useSelector(clinicItemSelector);
    // eslint-disable-next-line react-hooks/rules-of-hooks
    const t = useTranslations();
    // eslint-disable-next-line react-hooks/rules-of-hooks
    const user = useSelector(userSelector);
    const {
        query: { id }
        // eslint-disable-next-line react-hooks/rules-of-hooks
    } = useRouter();

    // eslint-disable-next-line react-hooks/rules-of-hooks
    useEffect(() => {
        if (id) {
           dispatch(fetchItemAction(id));
        }
    }, [id, user.id]);

    // console.log('Fetched data', clinicData);

    return (
        <>
            <Head>
                <title>DenTal Care - Clinics</title>
                <meta name="description" content="Generated by create next app"/>
                <link rel="icon" href="/images/logo-1.svg"/>
            </Head>

            <div className="page-title">
                <h1>
                    <Link href='/clinics' legacyBehavior>
                        <a className="btn">
                            <span className="back-to-list"></span>
                        </a>
                    </Link>
                    &nbsp;{t('Edit Clinic')}
                </h1>
            </div>
            <div className="page-content">
                <div className="card">
                    {user?.id && <AddClinic locale={locale}  />}
                </div>
            </div>
        </>
    );
}

export async function getServerSideProps(context: any) {
    const {locale} = context;
    const session = await getSession(context);

    if (!session) {
        return {
            redirect: {destination: `/${locale === 'fr' ? '' : `${locale}/`}auth/signin`}
        };
    }

    return {
        props: {
            session,
            locale,
            messages: {
                ...require(`../../messages/${locale}.json`)
            }
        }
    };
}
