import Head from 'next/head';
import Link from 'next/link';
import Image from 'next/image';
import Router from 'next/router';
import { getSession } from 'next-auth/react';
import { useTranslations } from 'next-intl';
import React, { useEffect, useState, useCallback } from 'react';
import { useDispatch, useSelector } from 'react-redux';
import { paginatedItemsSelector, showDatePopupSelector } from '@/redux/dashboard/selectors';
import { paginationSelectorFactory } from '@/redux/layouts/selectors';
import { userSelector } from '@/redux/user/selectors';
import { fetchItemsAction, showDateSelectorAction, showPopupAction } from '@/redux/dashboard';
import { setPaginationAction } from '@/redux/layouts';
import { PaginationType } from '@/constants';
import { DateRangePicker } from 'react-date-range';
import moment from 'moment';

import 'react-date-range/dist/styles.css'; // main css file
import 'react-date-range/dist/theme/default.css'; // theme css file

export default function Index({ session, locale }: { session: any; locale: string }) {
    if (!session) return <></>;

    return (
        <>
            <Head>
                <title>DenTal Care - Dashboard</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/images/logo-1.svg" />
            </Head>

            <div className="page-title">
                <h1>Dashboard</h1>
            </div>
        </>
    );
}

export async function getServerSideProps(context: any) {
    const { locale } = context;
    const session = await getSession(context);
    console.log('Kakogo hera', session);
    if (!session) {
        return {
            redirect: { destination: `/${locale === 'fr' ? '' : `${locale}/`}auth/signin` }
        };
    }

    return {
        props: {
            session,
            locale,
            messages: {
                ...require(`../../messages/${locale}.json`)
            }
        }
    };
}
